git:
  depth: 1
os:
- osx
language: node_js
node_js:
- 6.7.0
install:
- npm install
- cd script && npm install && cd ..
- sh travis_before_script.sh
script: script/build --compress-artifacts
cache:
  directories:
  - electron
  - node_modules
  - apm/node_modules
  - script/node_modules
  - attach-package
  - ~/.thera/compile-cache
notifications:
  email:
    recipients:
    - huc1011@gmail.com
    - hzdengxu@163.com
    - 1032419360@qq.com
    on_failure: always